[project]
name = "cb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "typer>=0.20.0",
]

[tool.uv]
package = true

[project.scripts]
cb = "main:main"
